name: "tagged-release"

on:
  push:
    paths-ignore:
      - '.github/**'
    tags-ignore:
      - '*.*'
    branches:
      - master

jobs:
  tagged-release:
    name: "Tagged Release"
    
    strategy:
      matrix:
        # Use these Java versions
        java: [ '17' ]
        # and run on both Linux and Windows
        os: [ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v2.4.0
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: Orderly
          path: |
            build/libs/*.jar
